# -*- coding: utf-8 -*-
"""Module 5 practice

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13iBV1XeXPSLychklFdHqsMd2-y2mPmSd
"""

def print_message(message):
    print(message)

print("Braydon")
print_message("Hello")

def even_or_odd(a, b):
    total = a + b

    if total % 2 == 0:
        print(f"The sum is even")
    else:
        print(f"The sum is odd.")
even_or_odd(-43,81)

def celsius(f):
  temp = (f - 32)* 5/9
  print(temp)
celsius(63)

def leap_year(year):
    if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
        print(f"{year} is a leap year.")
    else:
        print(f"{year} is not a leap year.")
leap_year(2032)

def chinese_zodiac(year):
    zodiac_num = (year - 1900) % 12

    if zodiac_num == 0:
        print("Rat")
    elif zodiac_num == 1:
        print("Ox")
    elif zodiac_num == 2:
        print("Tiger")
    elif zodiac_num == 3:
        print("Rabbit")
    elif zodiac_num == 4:
        print("Dragon")
    elif zodiac_num == 5:
        print("Snake")
    elif zodiac_num == 6:
        print("Horse")
    elif zodiac_num == 7:
        print("Sheep")
    elif zodiac_num == 8:
        print("Monkey")
    elif zodiac_num == 9:
        print("Rooster")
    elif zodiac_num == 10:
        print("Dog")
    elif zodiac_num == 11:
        print("Pig")
chinese_zodiac(2073)

import pandas as pd
df = pd.read_csv('senator_tweets.csv')

df.head()

df['char_count'] = df['text'].str.len()

df[['char_count', 'replies', 'retweets', 'favorites']].corr()

df.loc[df['char_count'].idxmin(), 'text']

immigration_tweets = df[df['text'].str.contains('immigration', case=False, na=False)]

immigration_tweets.shape

canada_tweets = df[df['text'].str.contains('Canada', case=False, na=False)]

canada_tweets.shape

count_2010 = (pd.to_datetime(df['created_at']).dt.year == 2010).sum()
print(count_2010)

df['month'] = pd.to_datetime(df['created_at']).dt.month_name()

df.head()

df['month'].value_counts()

df['word_count'] = df['text'].str.split().str.len()

df.groupby('state')['word_count'].mean().sort_values(ascending=False)

df2 = pd.read_csv('invoice_lines.csv')

df2.head()

df2['color'] = df2['Description'].str.extract(r'\(([A-Za-z]+)\)')

df2['color'].value_counts()

df2['size'] = df2['Description'].str.extract(r'\s([A-Z]+)$')

df2['size'].value_counts()